"""NEOFFICE FILE — Owned 100% by Neoservice. Not from upstream OCE.

Regional configuration for Switzerland (CH).

This pack provides everything an Estimator / OCE deployment needs to operate
in the Swiss construction market:

- Identity (CHF, FR/DE/IT trilingual, Swiss number format ``1'234.56``)
- Classification standards (CFC, eBKP-H, eBKP-T, NPK + cross-references)
- SIA norms (102/103/108/118/122-126/416/421/451)
- TVA rules (8.1% standard / 2.6% reduced / 3.8% accommodation, 2024+)
- Swiss contract types (Forfait, Régie, Unité, Prix global, EG/ET)
- CN 2026-2031 labor classes (CE/Q/A/B/C)
- Social charges (OFAS 2026)
- SUVA accident insurance (class 41A construction)
- KBOB material indices reference

Bulk classification data (CFC/eBKP/NPK) is loaded from the sibling
``data/swiss_classifications.json`` file at module import time. The legal
notice required by CRB for derivative works is preserved verbatim from
the source generator.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_DATA_DIR = Path(__file__).parent / "data"
_CLASSIFICATIONS_PATH = _DATA_DIR / "swiss_classifications.json"


def _load_classifications() -> dict[str, Any]:
    """Load the CFC/eBKP/NPK bundle generated by ``swiss-refdata`` exporter."""
    if not _CLASSIFICATIONS_PATH.exists():
        return {
            "schema_version": "1.0",
            "catalogs": {"CFC": [], "eBKP-H": [], "eBKP-T": [], "NPK": []},
            "keywords": [],
            "mappings": [],
            "legal_notice": "",
            "sipal_notice": "",
        }
    return json.loads(_CLASSIFICATIONS_PATH.read_text())


_CLASSIFICATIONS = _load_classifications()


def _build_classification_standards() -> list[dict[str, Any]]:
    """Convert the JSON catalogs into ``standards`` entries.

    Each catalog becomes a top-level entry under ``standards`` so it is
    discoverable via ``GET /standards/{code}/``. Mapping data and the NPK
    keyword index are exposed as separate top-level keys (see PACK_CONFIG).
    """
    catalogs = _CLASSIFICATIONS.get("catalogs", {})
    return [
        {
            "code": "CFC",
            "name": "CFC — Code des Frais de Construction (SIA 506 500)",
            "description": (
                "Swiss building cost plan. Hierarchical 4-level code "
                "(0 → 00 → 000 → 000.0). Lausanne 2023 reference + SIPaL "
                "Vaud cantonal extensions (marked is_sipal_specific=true)."
            ),
            "sia_reference": "SIA 506 500",
            "publisher": "Ville de Lausanne / SIPaL Vaud",
            "language": "fr",
            "entries": catalogs.get("CFC", []),
        },
        {
            "code": "eBKP-H",
            "name": "eBKP-H — Code des coûts de construction Bâtiment (SIA 506 511)",
            "description": (
                "Swiss element-based cost plan for buildings. 3-level "
                "alphanumeric (A → A01 → A01.01). Replaces the legacy "
                "eCCC-Bât name from the 2017 edition."
            ),
            "sia_reference": "SIA 506 511",
            "publisher": "CRB",
            "language": "fr",
            "entries": catalogs.get("eBKP-H", []),
        },
        {
            "code": "eBKP-T",
            "name": "eBKP-T — Code des coûts de construction Génie Civil (SIA 506 512)",
            "description": (
                "Swiss element-based cost plan for civil engineering. "
                "3-level (A → A 1 → A 1.1). Replaces the legacy eCCC-GC "
                "name from the 2017 edition."
            ),
            "sia_reference": "SIA 506 512",
            "publisher": "CRB",
            "language": "fr",
            "entries": catalogs.get("eBKP-T", []),
        },
        {
            "code": "NPK",
            "name": "NPK — Catalogue des articles normalisés (CRB)",
            "description": (
                "Swiss normalised work-item catalogue. ~150 chapters in "
                "FR/DE/IT. Each NPK chapter has an edition year (e.g. F/14 "
                "= French edition 2014). The keyword index allows lookup "
                "from natural-language work descriptions."
            ),
            "sia_reference": None,
            "publisher": "CRB",
            "language": "fr",
            "entries": catalogs.get("NPK", []),
        },
    ]


# ── SIA norms ─────────────────────────────────────────────────────────────
# Hand-curated reference data. Numeric values (fee shares, multipliers) are
# orientation values from the 2014/2020 SIA editions and are non-binding
# since the Swiss federal court ruling on cartel-like fee tables.

_SIA_STANDARDS: list[dict[str, Any]] = [
    {
        "code": "SIA_102",
        "name": "SIA 102 — Règlement concernant les prestations et honoraires des architectes",
        "description": (
            "Reference fee schedule for architects. Phases SIA 102 mirror "
            "the 11 SIA phases (study → tendering → execution → commissioning)."
        ),
        "sia_reference": "SIA 102 (2020)",
        "service_phases": [
            {"phase": "1", "title": "Définition des objectifs", "subphase": "1.1", "fee_share_pct": "2"},
            {"phase": "2", "title": "Études préliminaires", "subphase": "2.1", "fee_share_pct": "3"},
            {"phase": "3", "title": "Étude du projet", "subphase": "3.1", "fee_share_pct": "21"},
            {"phase": "3", "title": "Étude du projet — avant-projet", "subphase": "3.1", "fee_share_pct": "9"},
            {"phase": "3", "title": "Étude du projet — projet de l'ouvrage", "subphase": "3.2", "fee_share_pct": "21"},
            {"phase": "3", "title": "Étude du projet — procédure de demande d'autorisation", "subphase": "3.3", "fee_share_pct": "5"},
            {"phase": "4", "title": "Appel d'offres", "subphase": "4.1", "fee_share_pct": "12"},
            {"phase": "5", "title": "Réalisation", "subphase": "5.1", "fee_share_pct": "44"},
            {"phase": "5", "title": "Réalisation — projet d'exécution", "subphase": "5.1", "fee_share_pct": "15"},
            {"phase": "5", "title": "Réalisation — exécution", "subphase": "5.2", "fee_share_pct": "26"},
            {"phase": "5", "title": "Réalisation — mise en service", "subphase": "5.3", "fee_share_pct": "3"},
        ],
        "note": (
            "Honoraires = orientation, non contraignants. Catégories d'ouvrage I-VI. "
            "Coefficients r (proportionnel), q (qualité), n (catégorie), "
            "i (modalité de calcul) — voir SIA 102 art. 7."
        ),
    },
    {
        "code": "SIA_103",
        "name": "SIA 103 — Règlement des prestations et honoraires des ingénieurs civils",
        "description": "Reference fee schedule for civil engineers (structural, geotechnical).",
        "sia_reference": "SIA 103 (2020)",
        "note": "Mêmes phases que SIA 102, adaptées aux prestations d'ingénierie civile.",
    },
    {
        "code": "SIA_108",
        "name": "SIA 108 — Règlement des prestations et honoraires des ingénieurs CVCR",
        "description": "Fee schedule for HVAC, sanitary, refrigeration engineers.",
        "sia_reference": "SIA 108 (2020)",
        "note": "Couvre Chauffage, Ventilation, Climatisation, Réfrigération, Sanitaire.",
    },
    {
        "code": "SIA_118",
        "name": "SIA 118 — Conditions générales pour l'exécution des travaux de construction",
        "description": (
            "General contract conditions, the Swiss equivalent of VOB/B. "
            "Covers warranty periods (Garantie 2 ans), rules around variations "
            "and payment, defects liability, etc."
        ),
        "sia_reference": "SIA 118 (2013)",
        "warranty_years": 2,
        "defect_liability_years": 5,
        "note": (
            "Référence quasi-systématique en marchés privés et publics CH. "
            "L'art. 158 prévoit délai de garantie 2 ans (5 ans pour défauts cachés)."
        ),
    },
    {
        "code": "SIA_122",
        "name": "SIA 122 — Norme contractuelle MP (Mode de Paiement)",
        "description": "Contractual norm for price-update method MP (renchérissement).",
        "sia_reference": "SIA 122 (2014)",
        "use_case": "Marchés de gré à gré et concours pour bâtiment.",
    },
    {
        "code": "SIA_124",
        "name": "SIA 124 — Norme contractuelle MPJ (Mode de Paiement par Justificatifs)",
        "description": "Price-update method based on justified costs (paie selon dépenses).",
        "sia_reference": "SIA 124 (2014)",
        "use_case": "Marchés où les coûts réels sont reportés au maître d'ouvrage.",
    },
    {
        "code": "SIA_125",
        "name": "SIA 125 — Norme contractuelle MP-EG/ET (entreprises générales/totales)",
        "description": "Price-update for general/total contractors (EG/ET).",
        "sia_reference": "SIA 125 (2014)",
        "use_case": "Marchés à entreprise générale (EG) ou entreprise totale (ET).",
    },
    {
        "code": "SIA_126",
        "name": "SIA 126 — Norme contractuelle MP-PM (mandataires)",
        "description": "Price-update for design and engineering mandate contracts.",
        "sia_reference": "SIA 126 (2014)",
        "use_case": "Honoraires architectes/ingénieurs.",
    },
    {
        "code": "SIA_416",
        "name": "SIA 416 — Surfaces et volumes des bâtiments",
        "description": "Building surfaces and volumes — the Swiss measurement standard.",
        "sia_reference": "SIA 416 (2003)",
    },
    {
        "code": "SIA_421",
        "name": "SIA 421 — Standards d'échange de données BIM",
        "description": "BIM data exchange. References IFC and CDE workflows.",
        "sia_reference": "SIA 421",
    },
    {
        "code": "SIA_451",
        "name": "SIA 451 — Format d'échange de données BAU",
        "description": (
            "Swiss data exchange format for tendering and BOQ; equivalent of "
            "the German GAEB XML. Used by libracore DataExpert and others."
        ),
        "sia_reference": "SIA 451",
    },
]


# ── Pack configuration ────────────────────────────────────────────────────

PACK_CONFIG: dict[str, Any] = {
    # ── Identity ─────────────────────────────────────────────────────────
    "region_code": "CH",
    "countries": ["CH"],
    "default_currency": "CHF",
    "supported_locales": ["fr", "de", "it"],
    "default_locale": "fr",
    "measurement_system": "metric",
    "paper_size": "A4",
    "date_format": "DD.MM.YYYY",
    # Swiss number format: apostrophe as thousands separator, dot as decimal.
    # Example: 1'234'567.89
    "number_format": "1'234.56",
    # ── Display name in 3 official languages ────────────────────────────
    "display_name_i18n": {
        "fr": "Suisse",
        "de": "Schweiz",
        "it": "Svizzera",
    },
    # ── Standards (classifications + SIA norms) ─────────────────────────
    "standards": _build_classification_standards() + _SIA_STANDARDS,
    # ── NPK keyword index (for natural-language work-item lookup) ───────
    "npk_keywords": _CLASSIFICATIONS.get("keywords", []),
    # ── Cross-reference mappings between catalogs ───────────────────────
    "cross_references": _CLASSIFICATIONS.get("mappings", []),
    # ── Tax rules — TVA Suisse ──────────────────────────────────────────
    # Rates effective 2024-01-01 per the Swiss federal AVS reform.
    "tax_rules": [
        {
            "code": "CH_TVA_STANDARD",
            "name": "TVA — Taux normal",
            "name_i18n": {
                "fr": "TVA — Taux normal",
                "de": "MwSt — Normalsatz",
                "it": "IVA — Aliquota normale",
            },
            "type": "vat",
            "country": "CH",
            "rate_pct": "8.1",
            "effective_from": "2024-01-01",
            "use_case": "Standard rate for construction work, materials, equipment.",
        },
        {
            "code": "CH_TVA_REDUCED",
            "name": "TVA — Taux réduit",
            "name_i18n": {
                "fr": "TVA — Taux réduit",
                "de": "MwSt — Reduzierter Satz",
                "it": "IVA — Aliquota ridotta",
            },
            "type": "vat",
            "country": "CH",
            "rate_pct": "2.6",
            "effective_from": "2024-01-01",
            "use_case": (
                "Food, books, medicines, agriculture inputs. "
                "Generally NOT applicable to construction; included for "
                "invoicing completeness."
            ),
        },
        {
            "code": "CH_TVA_ACCOMMODATION",
            "name": "TVA — Taux spécial hébergement",
            "name_i18n": {
                "fr": "TVA — Taux spécial hébergement",
                "de": "MwSt — Sondersatz Beherbergung",
                "it": "IVA — Aliquota speciale alloggio",
            },
            "type": "vat",
            "country": "CH",
            "rate_pct": "3.8",
            "effective_from": "2024-01-01",
            "use_case": "Hotels, lodging — applicable only for short-term accommodation services.",
        },
    ],
    # ── Contract types ──────────────────────────────────────────────────
    # Swiss construction contract types per SIA 118 + canton-level practice.
    "contract_types": [
        {
            "code": "CH_FORFAIT",
            "name": "Marché à prix forfaitaire",
            "name_i18n": {
                "fr": "Marché à prix forfaitaire",
                "de": "Pauschalpreisvertrag",
                "it": "Contratto a prezzo forfettario",
            },
            "description": (
                "Lump-sum contract: total price fixed for a defined scope. "
                "Risk on contractor for quantity variations."
            ),
            "sia_reference": "SIA 118 art. 39",
        },
        {
            "code": "CH_REGIE",
            "name": "Marché en régie",
            "name_i18n": {
                "fr": "Marché en régie",
                "de": "Regievertrag",
                "it": "Contratto in economia",
            },
            "description": (
                "Time-and-materials contract: hourly rates for labor + cost of "
                "materials. Common for unforeseen work, repairs, small jobs."
            ),
            "sia_reference": "SIA 118 art. 44-49",
        },
        {
            "code": "CH_UNITE",
            "name": "Marché à prix unitaires",
            "name_i18n": {
                "fr": "Marché à prix unitaires",
                "de": "Einheitspreisvertrag",
                "it": "Contratto a prezzi unitari",
            },
            "description": (
                "Unit-price contract: fixed unit prices, paid per actual "
                "quantities measured. Most common for civil engineering works."
            ),
            "sia_reference": "SIA 118 art. 38",
        },
        {
            "code": "CH_PRIX_GLOBAL",
            "name": "Marché à prix global",
            "name_i18n": {
                "fr": "Marché à prix global",
                "de": "Globalpreisvertrag",
                "it": "Contratto a prezzo globale",
            },
            "description": (
                "Global price contract: fixed total but with provision for "
                "specific adjustments (renchérissement, variations expressly "
                "listed). Hybrid between forfait and unité."
            ),
            "sia_reference": "SIA 118 art. 40",
        },
        {
            "code": "CH_EG_ENTREPRISE_GENERALE",
            "name": "Entreprise générale (EG)",
            "name_i18n": {
                "fr": "Entreprise générale (EG)",
                "de": "Generalunternehmer (GU)",
                "it": "Impresa generale (IG)",
            },
            "description": (
                "General contractor delivers the construction works under a "
                "single contract. Designs already done by the client side."
            ),
            "sia_reference": "SIA 118 / SIA 125",
        },
        {
            "code": "CH_ET_ENTREPRISE_TOTALE",
            "name": "Entreprise totale (ET)",
            "name_i18n": {
                "fr": "Entreprise totale (ET)",
                "de": "Totalunternehmer (TU)",
                "it": "Impresa totale (IT)",
            },
            "description": (
                "Total contractor delivers design + construction under a "
                "single contract — design-build."
            ),
            "sia_reference": "SIA 118 / SIA 125",
        },
    ],
    # ── Payment templates ───────────────────────────────────────────────
    "payment_templates": [
        {
            "code": "CH_ACOMPTE",
            "name": "Acompte / Décompte intermédiaire",
            "name_i18n": {
                "fr": "Acompte / Décompte intermédiaire",
                "de": "Anzahlung / Akontozahlung",
                "it": "Acconto / Conto intermedio",
            },
            "description": "Interim invoice for work-in-progress per SIA 118 art. 144.",
            "fields": [
                "invoice_number",
                "period",
                "contract_sum",
                "variations_sum",
                "adjusted_contract_sum",
                "cumulative_work_done",
                "previous_payments",
                "current_claim",
                "retainage_pct",
                "retainage_amount",
                "net_payment",
                "tva_pct",
                "tva_amount",
                "gross_payment",
            ],
        },
        {
            "code": "CH_DECOMPTE_FINAL",
            "name": "Décompte final",
            "name_i18n": {
                "fr": "Décompte final",
                "de": "Schlussabrechnung",
                "it": "Conto finale",
            },
            "description": "Final invoice closing the contract per SIA 118 art. 154-156.",
        },
        {
            "code": "CH_DECOMPTE_MESURE",
            "name": "Décompte de mesure",
            "name_i18n": {
                "fr": "Décompte de mesure",
                "de": "Aufmaßabrechnung",
                "it": "Conto a misura",
            },
            "description": (
                "Measurement-based invoice for unit-price contracts. "
                "Quantities measured on site multiplied by unit prices."
            ),
        },
    ],
    # ── Labor classes (CN 2026-2031) ────────────────────────────────────
    # Swiss collective bargaining agreement for the construction sector,
    # signed 12.12.2025, effective 2026-01-01 to 2031-12-31. Hourly rates
    # are placeholders (real values vary by canton) — to be enriched by
    # the swiss-refdata `cn_sse_pdf` parser when available.
    "labor_classes": [
        {
            "code": "CN_CE",
            "name": "Chef d'équipe / Polier",
            "name_i18n": {
                "fr": "Chef d'équipe",
                "de": "Polier / Vorarbeiter",
                "it": "Capo squadra",
            },
            "description": "Foreman / lead worker leading a team on site.",
            "level": 5,
        },
        {
            "code": "CN_Q",
            "name": "Ouvrier qualifié (Q)",
            "name_i18n": {
                "fr": "Ouvrier qualifié",
                "de": "Qualifizierter Berufsmann",
                "it": "Operaio qualificato",
            },
            "description": "Qualified construction worker with CFC/AFP certificate.",
            "level": 4,
        },
        {
            "code": "CN_A",
            "name": "Ouvrier de classe A",
            "description": "Skilled worker, ≥ 3 years experience.",
            "level": 3,
        },
        {
            "code": "CN_B",
            "name": "Ouvrier de classe B",
            "description": "Construction worker with some experience.",
            "level": 2,
        },
        {
            "code": "CN_C",
            "name": "Ouvrier de classe C / Manœuvre",
            "name_i18n": {
                "fr": "Manœuvre",
                "de": "Bauhilfsarbeiter",
                "it": "Manovale",
            },
            "description": "Unskilled worker / labourer.",
            "level": 1,
        },
    ],
    # ── Social charges (OFAS 2026 — federal Swiss rates) ────────────────
    # These are mandatory federal contributions; cantonal variations exist
    # for LAA, LPP, AANP and family allowances (CAF).
    "social_charges": {
        "year": 2026,
        "components": [
            {
                "code": "AVS_AI_APG",
                "name": "AVS + AI + APG (1er pilier)",
                "name_i18n": {
                    "fr": "AVS + AI + APG (1er pilier)",
                    "de": "AHV + IV + EO (1. Säule)",
                },
                "employer_pct": "5.3",
                "employee_pct": "5.3",
                "publisher": "OFAS",
            },
            {
                "code": "AC",
                "name": "Assurance chômage",
                "name_i18n": {"fr": "Assurance chômage", "de": "Arbeitslosenversicherung"},
                "employer_pct": "1.1",
                "employee_pct": "1.1",
                "salary_cap": "148200",
                "publisher": "OFAS",
            },
            {
                "code": "LAA_PRO",
                "name": "LAA — accidents professionnels",
                "name_i18n": {"fr": "LAA accidents professionnels", "de": "BU-Versicherung"},
                "employer_pct": "varies",
                "employee_pct": "0",
                "publisher": "SUVA",
                "note": "Construction = SUVA classe 41A (~1.5-3% selon entreprise).",
            },
            {
                "code": "LAA_NONPRO",
                "name": "LAA — accidents non professionnels",
                "name_i18n": {"fr": "LAA accidents non professionnels", "de": "NBU-Versicherung"},
                "employer_pct": "0",
                "employee_pct": "varies",
                "publisher": "SUVA",
                "note": "À charge employé; employeur peut prendre en charge.",
            },
            {
                "code": "LPP",
                "name": "LPP / Prévoyance professionnelle (2e pilier)",
                "name_i18n": {"fr": "LPP — Prévoyance professionnelle", "de": "BVG — Berufliche Vorsorge"},
                "employer_pct": "varies",
                "employee_pct": "varies",
                "publisher": "OFAS",
                "note": (
                    "Taux variable selon âge: 7% (25-34), 10% (35-44), "
                    "15% (45-54), 18% (55-65). Partage min 50/50."
                ),
            },
            {
                "code": "CAF_AF",
                "name": "Caisse d'allocations familiales",
                "name_i18n": {"fr": "Allocations familiales", "de": "Familienzulagen"},
                "employer_pct": "varies",
                "publisher": "Cantonal",
                "note": "Cantonal — Vaud ~2.0%, Genève ~2.5%, Berne ~1.7%.",
            },
        ],
    },
    # ── SUVA accident insurance class for construction ──────────────────
    "suva_class": {
        "code": "41A",
        "name": "SUVA Classe 41A — Construction",
        "description": (
            "Mandatory class for construction businesses (gros œuvre + "
            "second œuvre). Net base rate published annually by SUVA."
        ),
        "publisher": "SUVA",
        "reference_document": "SUVA 335.f",
        "note": (
            "Taux net de base ~1.5-3.0% selon expérience-incidents et "
            "branche détaillée. Suppléments AANP cantonaux."
        ),
    },
    # ── KBOB indices reference ──────────────────────────────────────────
    "kbob_indices": {
        "publisher": "KBOB / OFS",
        "url_hub": "https://www.bfs.admin.ch/asset/fr/su-f-05.04-kbob-01",
        "guide_contractual": (
            "https://www.kbob.admin.ch/dam/fr/sd-web/5SPO9Vd9uCrT/"
            "20221209_KBOB-Leitfaden_Vertragsteuerung_Dezember_2022_"
            "Publikation_FR.pdf"
        ),
        "guide_precontractual": (
            "https://www.kbob.admin.ch/dam/fr/sd-web/QKj7peuFfOMH/"
            "20240909_KBOB-Leitfaden_Vorvertragsteuerung_bei_"
            "Bauvorhaben_V2.0_Publikation_FR.pdf"
        ),
        "formulas": [
            {
                "code": "MP_SIA_122",
                "name": "Formulaire de calcul MP (SIA 122)",
                "description": "Bâtiment, marchés gré à gré et concours.",
            },
            {
                "code": "MP_SIA_125",
                "name": "Formulaire MP-EG/ET (SIA 125)",
                "description": "Entreprises générales et totales.",
            },
            {
                "code": "MP_SIA_126",
                "name": "Formulaire MP-PM (SIA 126)",
                "description": "Mandats de prestations (architectes, ingénieurs).",
            },
            {
                "code": "MPJ_SIA_124",
                "name": "Formulaire MPJ (SIA 124)",
                "description": "Mode de paiement par justificatifs.",
            },
        ],
        "note": (
            "Indices matériaux publiés mensuellement par KBOB (via OFS). "
            "Indices salaires second œuvre publiés semestriellement."
        ),
    },
    # ── Default units (metric) ──────────────────────────────────────────
    "default_units": {
        "length": "m",
        "area": "m²",
        "volume": "m³",
        "weight": "kg",
        "temperature": "°C",
        "labor": "h",
        "machine": "h-machine",
    },
    # ── Sub-pack metadata for upstream traceability ─────────────────────
    "metadata": {
        "schema_version": _CLASSIFICATIONS.get("schema_version", "1.0"),
        "generator_version": _CLASSIFICATIONS.get("generator_version", "0.0.0"),
        "generated_on": _CLASSIFICATIONS.get("generated_on", ""),
        "legal_notice": _CLASSIFICATIONS.get("legal_notice", ""),
        "sipal_notice": _CLASSIFICATIONS.get("sipal_notice", ""),
        "source_subproject": "neoconstruction/swiss-refdata",
    },
}


# ── Public helpers ────────────────────────────────────────────────────────


def get_standard_by_code(code: str) -> dict[str, Any] | None:
    """Return a single standard entry by its ``code`` field, or None."""
    for std in PACK_CONFIG["standards"]:
        if std["code"] == code:
            return std
    return None


def get_classifications_summary() -> dict[str, Any]:
    """Compact summary of code+label across CFC/eBKP/NPK (no metadata).

    Suitable for autocomplete dropdowns or quick code lookup. Returns a
    dict keyed by catalog code, with each value a list of
    ``{code, label_fr, level}`` entries. Total payload typically <100 KB.
    """
    summary: dict[str, Any] = {}
    for std in PACK_CONFIG["standards"]:
        if std["code"] not in {"CFC", "eBKP-H", "eBKP-T", "NPK"}:
            continue
        summary[std["code"]] = [
            {
                "code": entry.get("code"),
                "label_fr": (entry.get("label") or {}).get("fr"),
                "level": entry.get("level"),
                "is_sipal_specific": entry.get("is_sipal_specific", False),
            }
            for entry in std.get("entries", [])
        ]
    return summary
